### ISSUE TITLE
CREATE_FAILED Error After Remove KMS References

### ISSUE THREAD

**Issue by jasebas** [aws-quickstart/quickstart-trek10-serverless-enterprise-cicd#10]
1. Following document to try out CICD cross account. https://github.com/aws-quickstart/quickstart-trek10-serverless-enterprise-cicd
2. Removed KMS references (not required for our use case).  See cloudformation yaml are copy into s3://catt-dev-developer-resources/jamie51
3. Received 'stack failed' error after deploying nested cloudformation , project.template.yaml,
4 Keep the Roll Back to NO, so all the resources are available for inspected 
5. Loading the full-stack.template.yaml to create stack via aws console and fill out all appropriate parameters
6. already successfully create ChildAccountRole.yaml acrross two other account
7 Thank you for your help

Error stack :

CREATE_FAILED 	AWS::CloudFormation::Stack 	cicd-serverless-quickstart-ProjectPipelineStack-10KW917CBPQP9 	The following resource(s) failed to create: [Pipeline].
	18:35:25 UTC+0000 	CREATE_FAILED 	AWS::CodePipeline::Pipeline 	Pipeline 	arn:aws:iam::162078207059:role/cicd-serverless-quickstart-Acc-PipelineServiceRole-15H1EL7H5XXN0 is not authorized to perform AssumeRole on role arn:aws:iam::162078207059:role/CodePipelineServiceRole-us-east-1-162078207059-dev (Service: AWSCodePipeline; Status Code: 400; Error Code: InvalidStructureException; Request ID: a50f8612-c08f-43c5-a294-335a2db69690)
Stack ID(s) / Stack ARN: arn:aws:cloudformation:us-east-1:162078207059:stack/cicd-serverless-quickstart-ProjectPipelineStack-10KW917CBPQP9/28939550-7bf7-11e9-a8e5-0ab87eb901cc

**Comment by awarzon** [comment]
Solving this would require the same feature enhancement being discussed in #9 . @jayyeras I suggest we close this and continue this discussion in #9

**Comment by jayyeras** [comment]
@awarzon closing as requested.
