### ISSUE TITLE
CREATED_FAILED at project.template.yaml

### ISSUE THREAD

**Issue by jlpl1999** [aws-quickstart/quickstart-trek10-serverless-enterprise-cicd#11]
- Due to restriction on IAM role, there is no ability to  create IAM::User. 

- Commented out line 179 in project.template.yaml and several area that has a reference to that

- Any suggestion, to pass this stage, WITHOUT create IAM::User ?
- Thank you for your support

**Comment by awarzon** [comment]
Thanks for trying this quickstart @jlpl1999 . You could comment out the whole resource `CodecommitCredentialsLambda` L577 to L612, this means that the CodeCommit repo will be created but no user to access it. Then I suggest you review the CodeCommit documentation regarding [Authentication and Access Control](https://docs.aws.amazon.com/codecommit/latest/userguide/auth-and-access-control.html) to determine a strategy that will work for you and whomever controls the permissions you have available to you.

**Comment by jayyeras** [comment]
@awarzon is this one good to close?

**Comment by jlpl1999** [comment]
yes please

**Comment by jayyeras** [comment]
Closing as requested.
