### ISSUE TITLE
Branch-pipeline Lambda referencing wrong template name

### ISSUE THREAD

**Issue by juhoj** [aws-quickstart/quickstart-trek10-serverless-enterprise-cicd#3]
The environment variable in the Lambda function that creates the branches should reference this file in S3: "https://aws-quickstart.s3.amazonaws.com/quickstart-trek10-serverless-enterprise-cicd/templates/pipeline.template.yaml". Now it's referencing "https://aws-quickstart.s3.amazonaws.com/quickstart-trek10-serverless-enterprise-cicd/templates/pipeline.yaml" that doesn't exist

**Comment by awarzon** [comment]
Fixed in https://github.com/aws-quickstart/quickstart-trek10-serverless-enterprise-cicd/pull/5
