### ISSUE TITLE
Feature branch name patterns like "feature/..." are not taken into account correctly

### ISSUE THREAD

**Issue by TLaue** [aws-quickstart/quickstart-trek10-serverless-enterprise-cicd#4]
A pipeline created for a feature branch named following a pattern like "feature/myNewFeature" does not run as the "Source fetching stage" does not specify the branch name correctly. This might be a bug or a feature but at least it should be documented.

Source of the problem: LambdaS-DynamicPipelineMakerLamb
line 69: `branch = reference['ref'].split('/')[-1]`

**Comment by awarzon** [comment]
Thanks @TLaue for using this Quickstart. Does https://github.com/aws-quickstart/quickstart-trek10-serverless-enterprise-cicd/pull/14 solve this for you?

**Comment by TLaue** [comment]
Hello,

this PR fixes the above mentioned problem. 

Thanks!
